@startuml

actor Trader
participant "Strategy" as Strategy
participant "Market" as Market

Trader -> Market: Set Price data
activate Market

Trader -> Strategy: Set Parameter \nand cash
activate Strategy
Strategy -> Market: Reset portofolio

Trader -> Strategy: Start backtest
loop
    
    Strategy -> Market: Update index
    Strategy -> Market: Request \nCurrent Price
    Market --> Strategy: Current Price

    Strategy -> Strategy: Generate Signals

    Strategy -> Market: Place Order
    Market -> Market: Try execute Oder
    Market --> Strategy: Order Result
end
Strategy --> Trader: Backtest Result
deactivate Strategy

@enduml
